#version 460 core

layout(binding = 0, r8) uniform readonly image2D original_image;

layout(binding = 1, r8) uniform writeonly image2D output_image;

layout(local_size_x = 32, local_size_y = 32) in;

void main() {
  const ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
  if (any(greaterThanEqual(coord, imageSize(original_image)))) {
    return;
  }
  imageStore(output_image, coord, imageLoad(original_image, coord));
}
