package(default_visibility = ["//lighter:__subpackages__"])

cc_library(
    name = "renderer",
    hdrs = ["renderer.h"],
    srcs = ["renderer.cc"],
    deps = [
        "//lighter/renderer",
    ],
)
