package(default_visibility = ["//jessie_steamer/application/vulkan/aurora:__subpackages__"])

cc_library(
    name = "viewer",
    hdrs = ["viewer.h"],
    srcs = ["viewer.cc"],
    deps = [
        "//jessie_steamer/application/vulkan/aurora:scene",
        "//jessie_steamer/application/vulkan:common",
    ],
)